version: "3.8"

services:
  chat-tts-forge-api:
    build: .
    container_name: chat-tts-forge-api
    restart: always
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    command: >
      python3 launch.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
